name: Node.js Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:lts-hydrogen
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Set up PostgreSQL database
        run: node postgres_setup.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
      - name: Test Redis
        run: node redis.js
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
      - name: Build
        run: npm run build
      - name: Run node server 
        run: npm run runServerAction
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379

